export const API_KEY_KEY = 'apiKey'
export const AUTO_PLAY_ENABLED = 'autoPlayEnabled'
export const NOW_PLAYING_HEIGHT = 'nowPlayingHeight'
export const ALL_SUBS_MARKED_VIDEO_ID = 'allSubsMarkedVideoId'
export const SUBS_KEY = 'subs'
