// Generated by CoffeeScript 1.4.0
(function() {
  var chai, fs, requirejs;

  chai = require('chai');

  global.expect = chai.expect;

  chai.Assertion.includeStack = true;

  global.jQuery = require('jquery');

  global.requirejs = requirejs = require('requirejs');

  require('./configure-require.js');

  fs = require('fs');

  global.define = requirejs;

}).call(this);
