// Generated by CoffeeScript 1.4.0
(function() {

  requirejs.config({
    nodeRequire: require,
    baseUrl: 'js',
    paths: {
      jquery: 'lib/jquery.min',
      underscore: 'lib/underscore.min',
      backbone: 'lib/backbone.min',
      localstorage: 'lib/backbone.localstorage.min',
      text: 'lib/require.text.min',
      handlebars: 'lib/handlebars.min',
      moment: 'lib/moment.min',
      template: '/templates'
    },
    shim: {
      backbone: {
        deps: ['jquery', 'underscore'],
        exports: 'Backbone'
      },
      underscore: {
        exports: '_'
      }
    }
  });

}).call(this);
